name = "PrePostCall"
uuid = "75ea050c-ac48-11e8-3ca6-5d0a9bde5671"
authors = ["Sebastian Pech <sebastian.pech@me.com>"]
version = "0.0.2"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
